[package]
name = "policy-version-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = "0.15"
clap = { version = "4.1", features = ["derive"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
versions = { path = "../versions" }
