on:
  push:
    branches:
      - main
    tags:
      - "v*"

name: Release policy

jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@36f0782e949d8597c061ca0d519f7e17a2813190 # v3.4.8

  check-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: check-policy-metadata
        shell: bash
        run: |
          make check-policy-metadata

  release:
    needs:
      - test
      - check-policy-metadata
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-rust.yml@36f0782e949d8597c061ca0d519f7e17a2813190 # v3.4.8
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/deprecated-api-versions
